export const BestSeller = [
    {
        id: 1,
        name: "T-Shirt Oversized Hell",
       image: "https://drive.google.com/uc?export=download&id=1RgoYyGeW6ytpUNov6rJR09lG9EyB9RQ_",
        price: 15,
        url : "",
        size: "Unica",
        material: "100% Algodon",
        care: "Lavadora o Limpieza en seco",
      },
      {
        id: 5,
        name: "Top Negro Estampado Rosas",
       image : "https://drive.google.com/uc?export=download&id=1IxFcPchD2JBK_fcb7A6vM5hBTQMfwQ3Q" /*`https://drive.google.com/uc?export=download&id=1czRgAVmB8OaHXwqsLn1lLzPyDTUGdFO9*/,
        price: 5,
        url:"",
        size: "M",
        material: "95% Poliéster, 5% Spandex",
        care: "Lavadora o Limpieza en seco Profesional",
      },
      {
      id: 8,
      name: "Lentes de Sol",
      image:"https://drive.google.com/uc?export=download&id=1nj66QhJ6vYWvwK2kJuSRm_FmdlpsDVj-",
      price: 5,
      url : "",
      size: "Unica",
      material: "",
      care: "Guardar en funda para evitar rayados",
    },
    {
      id: 9,
      name: "Collar Afroditas",
      image: "https://drive.google.com/uc?export=download&id=1ExYaV6xrmOXitw15SAuN4RwHPbT2Jg1T",
      price: 5,
      url : "",
      size: "Unica",
      material: "Acero Inoxidable",
      care: " Coloca tus piezas después de vestirte y después de que se hayan secado los productos que hayas utilizado.  ",
    },
]